# Generated by Django 2.2.10 on 2020-02-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AddField(
            model_name='problem',
            name='nov',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='tid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
