# Generated by Django 2.2.10 on 2020-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depress', '0003_auto_20200301_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='level',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.IntegerField(),
        ),
    ]
