# Generated by Django 2.2.10 on 2020-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depress', '0004_auto_20200301_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.IntegerField()),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='lid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
