# Generated by Django 2.2.10 on 2020-03-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depress', '0005_auto_20200301_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
